from klasa0616 import ksiazka

book = ksiazka('Lalka', 'Bolesław Prus', 350, 347)
book.open()
book.show_status()
book.next_page()
book.next_page()
book.previous_page()
book.next_page()
book.next_page()
book.next_page()
book.next_page()
book.show_status()
book.close()
book.next_page()
book.next_page()
book.previous_page()
